### ISSUE TITLE
Error importing zigpy_zboss.zigbee.application

### ISSUE THREAD

**Issue by willpuckett** [kardia-as/zigpy-zboss#27]
Running `import zigpy_zboss.zigbee.application`, I get the following error:

```
Python 3.11.5 (main, Sep 28 2023, 20:48:59) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zigpy_zboss.zigbee.application
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/zigpy_zboss/zigbee/application.py", line 14, in <module>
    import zigpy_zboss.types as t_zboss
  File "/usr/local/lib/python3.11/site-packages/zigpy_zboss/types/__init__.py", line 2, in <module>
    from .basic import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_zboss/types/basic.py", line 353, in <module>
    class enum_flag_uint8(enum_flag_factory(uint8_t)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_zboss/types/basic.py", line 303, in enum_flag_factory
    class _NewEnum(int_type, enum.Flag):
  File "/usr/local/lib/python3.11/site-packages/zigpy_zboss/types/basic.py", line 307, in _NewEnum
    enum.IntFlag._create_pseudo_member_.__func__
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: _create_pseudo_member_
>>>
```

Given my startling unfamiliarity with python, this could likely be a user error. Any pointers?

**Comment by willpuckett** [comment]
Closing as being tracked in #28 ...
