### ISSUE TITLE
network backup fix

### ISSUE THREAD

**Issue by DamKast** [kardia-as/zigpy-zboss#59]
Fix this:

```
Nov 04 12:28:21: 2024-11-04 12:28:21 WARNING (MainThread) [zigpy.backups] Failed to create a network backup
Nov 04 12:28:21: Traceback (most recent call last):
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy_zboss/api.py", line 226, in _send_to_uart
Nov 04 12:28:21:     return await response_future
Nov 04 12:28:21: asyncio.exceptions.CancelledError
Nov 04 12:28:21: During handling of the above exception, another exception occurred:
Nov 04 12:28:21: Traceback (most recent call last):
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy/backups.py", line 220, in _backup_loop
Nov 04 12:28:21:     await self.create_backup()
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy/backups.py", line 143, in create_backup
Nov 04 12:28:21:     await self.app.load_network_info(load_devices=load_devices)
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy_zboss/zigbee/application.py", line 359, in load_network_info
Nov 04 12:28:21:     common = await self._api.nvram.read(
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy_zboss/nvram.py", line 20, in read
Nov 04 12:28:21:     res = await self.zboss.request(
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy_zboss/api.py", line 206, in request
Nov 04 12:28:21:     return await self._send_frags(
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy_zboss/api.py", line 213, in _send_frags
Nov 04 12:28:21:     return await self._send_to_uart(frag, response_future, timeout)
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/zigpy_zboss/api.py", line 225, in _send_to_uart
Nov 04 12:28:21:     async with async_timeout.timeout(timeout):
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
Nov 04 12:28:21:     self._do_exit(exc_type)
Nov 04 12:28:21:   File "/usr/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
Nov 04 12:28:21:     raise asyncio.TimeoutError
Nov 04 12:28:21: asyncio.exceptions.TimeoutError
```

**Comment by DamKast** [comment]
This comes most likely from the retry decorator not present on the requests within the `load_network_info` method from the `ControllerApplication` class.
